services:
    api-zero:
        container_name: symfony
        build:
            context: .
            dockerfile: Dockerfile
        image: php83-fpm
        restart: unless-stopped
        working_dir: /var/www/
        environment:
            PHP_OPCACHE_ENABLE: 1
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            PHP_OPCACHE_MAX_ACCELERATED_FILES: 20000
            PHP_OPCACHE_MEMORY_CONSUMPTION: 256
            PHP_OPCACHE_MAX_WASTED_PERCENTAGE: 10
            PHP_OPCACHE_JIT_BUFFER_SIZE: "100M"
            PHP_OPCACHE_JIT: "tracing"
        volumes:
            - ./config/:/var/www/config:rw
            - ./src/:/var/www/src:rw
            - ./migrations/:/var/www/migrations:rw
            - ./var:/var/www/var
            - ./docker/php/conf.d/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
        networks:
            - api-network
    web-server:
        container_name: nginx
        image: nginx:1.24
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./ssl:/etc/nginx/ssl
        networks:
            - api-network
    db:
        container_name: postgres
        image: postgres:16
        restart: unless-stopped
        volumes:
            - "database_data:/var/lib/postgresql/data/"
        environment:
            POSTGRES_USER: ${DB_USERNAME} # The PostgreSQL user (useful to connect to the database)
            POSTGRES_PASSWORD: ${DB_PASSWORD} # The PostgreSQL password (useful to connect to the database)
            POSTGRES_DB: ${DB_DATABASE} # The PostgreSQL default database (automatically created at first launch)
        ports:
           - "5432:5432"
        networks:
            - api-network
    cache:
        container_name: redis
        image: redis:7
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - api-network
networks:
    api-network:
        driver: bridge
volumes:
    database_data: